[Feature][Task-44] 당첨자 관리 퍼블리싱
softeerbootcamp4th/Team4-newCar-FE pull request #13
Opened 2024-07-25 07:12 UTC by racgoo

## 🔘Part

- 어드민 페이지

  <br/>

## 🔎 작업 내용

- 선착순 이벤트 추첨 퍼블리싱
- 당첨자 리스트 퍼블리싱( 선착순, 경주 )

  <br/>

<br/>

2024-07-25 08:07 UTC, nimod7890 requested changes

2024-07-25 08:07 UTC, nimod7890 commented on packages/admin/src/pages/winner/WinnerResult.tsx
> +	const renderTab = () => {
switch-case도 괜찮을 것 같아요

2024-07-25 08:07 UTC, nimod7890 commented on packages/admin/src/pages/winner/WinnerResult.tsx
> +	const dummyData = new Array(200).fill(0).map((_, index) => new Array(5).fill(index * 2));
저희 페이지 구현할 때 mock server 까진 아니더라도 비동기 처리까지는 작업하고 완료하는게 좋을 것 같아요. 
어느정도 api 완성되면 최대한 빠르게 도입할 수 있는 구조까지는 추가로 구현해주시면 감사하겠습니다. api 구조 논의도 마침 끝났으니까요!

2024-07-25 08:10 UTC, racgoo commented on packages/admin/src/components/common/CommonPagination.tsx
> common prefix 제거하는 건 어떻게 생각하시나요? shadcn으로 생성되는 컴포넌트와 공통 컴포넌트에 대해서는 폴더만으로도 충분히 구분되지 않나 해서요. 대문자 여부도 그렇고요.
> 
> * Tab component에 대해서도 동일
넵 좋습니다~
import 편하게 하려고 하던 습관이 나왔네용

2024-07-25 08:12 UTC, racgoo commented on packages/admin/src/constants/TabName.ts
그것도 좋겠네요~

2024-07-25 08:23 UTC, racgoo commented on packages/admin/src/routes/router.tsx
>  			/* 페이지 컴포넌트 추가 */
Good~

2024-07-30 06:33 UTC, racgoo commented on packages/admin/src/pages/winner/WinnerResult.tsx
> +	const dummyData = new Array(200).fill(0).map((_, index) => new Array(5).fill(index * 2));
요건 사실 감이 잘 안와서 이벤트 페이지 보미님 작성하신거 참고해서 학습해볼게요!

2024-07-31 07:32 UTC, closed without merging