[Feature][Task-90] Admin 페이지 퍼블리싱 ( 기대평 관리 제외 )
softeerbootcamp4th/Team4-newCar-FE pull request #24
Opened 2024-07-30 06:31 UTC by racgoo

## 🔘Part

- 어드민 페이지

  <br/>

## 🔎 작업 내용

- 이벤트 관리 Tab (퍼블리싱)
- 당첨자 관리 Tab (퍼블리싱)
- 공통: ActionModal, AlertModal 제작 (ContextAPI를 사용하여 내부 컨텐츠만 바꾸는 방식)

2024-07-30 07:31 UTC, nimod7890 requested changes
수고하셨습니다! 
context api로 modal 관리하는 방식은 좋은데, 하나가 아닌 여러 개가 열릴 수 있도록 수정하시면 좋을 것 같습니다. 로직이 같은지는 모르겠는데 아래 링크 참고해도 좋을 것 같네요

https://velog.io/@haryan248/Context-API%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4-React-modal-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

추가로 https://github.com/softeerbootcamp4th/Team4-newCar-FE/pull/13
여기서 말씀드린 부분이 반영이 안 되어있어서 ,, (dummy 대신 mock api로 처리) 
mock 관련 처리 없이 admin api 서버 배포 기다렸다가 작업하실 예정인가요?

2024-07-30 07:31 UTC, nimod7890 commented on packages/admin/src/components/editor/QuizEventEditor.tsx
> +	const [quizName, setQuizName] = useState('');
useState 여러개 보다는 quiz event object로 관리하는 건 어떨까요?

2024-07-30 07:31 UTC, nimod7890 commented on packages/admin/src/components/appLayout/SideBar.tsx
> +	const hnadleClick = (path: string | undefined) => {
오타 수정해주세요

2024-07-30 07:42 UTC, racgoo commented
> 수고하셨습니다! context api로 modal 관리하는 방식은 좋은데, 하나가 아닌 여러 개가 열릴 수 있도록 수정하시면 좋을 것 같습니다. 로직이 같은지는 모르겠는데 아래 링크 참고해도 좋을 것 같네요
> 
> https://velog.io/@haryan248/Context-API%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4-React-modal-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0
> 
> 추가로 #13 여기서 말씀드린 부분이 반영이 안 되어있어서 ,, (dummy 대신 mock api로 처리) mock 관련 처리 없이 admin api 서버 배포 기다렸다가 작업하실 예정인가요?

넵 감사합니다. 해당 링크처럼 Props, Component를 지정해서 넘겨주는게 더 깔끔하고 코드도 이쁘네요! 
dummy 혹시 사용하시는 라이브러리나 방식이 있으시면 참고하고 싶습니다. 제가 mock 작업한 경험이 없어서 금일에 방식을 찾아볼게요!

2024-07-30 07:42 UTC, racgoo commented on packages/admin/src/components/appLayout/SideBar.tsx
> +	const hnadleClick = (path: string | undefined) => {
넵..... 쏘리...

2024-07-30 07:44 UTC, racgoo commented on packages/admin/src/components/editor/QuizEventEditor.tsx
> +	const [quizName, setQuizName] = useState('');
그게 더 편하겠네요! class방식에서 setState 했던 경험 살려서 useReducer로 변경해볼게요!

2024-07-31 07:11 UTC, nimod7890 approved these changes
엉엉 파일이 많아서 다 보진 못했는데..... 일단 고생하셨습니다 
동작 제대로 하는게 중요하니, api 연동 작업 끝내고 리팩토링할 때 다시 볼게요 
다음 PR부터는 나눠서 올려주시면 감사하겠습니다

2024-07-31 07:11 UTC, nimod7890 commented on package.json
> +		"@types/moment": "^2.13.0",
저도 moment 좋아해서 자주 썼는데, 요즘은 번들 사이즈 등을 이유로 day.js로 대체하는 추세더라고요

https://velog.io/@hamjw0122/%EC%9A%B0%EB%A6%AC%EA%B0%80-moment.js-%EB%8C%80%EC%8B%A0-day.js%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

2024-07-31 07:11 UTC, nimod7890 commented on packages/admin/src/components/editor/QuizEventEditor.tsx
> +
필수는 아니지만 이 부분은 key, value로 가져와서 처리하면 간단하게 사용할 수 있습니다
물론 이 방식이 사용할땐 간편해서 참고로만 알아두셔도 좋을 것 같아요

2024-07-31 07:22 UTC, racgoo commented on packages/admin/src/components/editor/QuizEventEditor.tsx
> +
넵 사실 불필요한 값 변경에도 업데이트가 일어나네요!! 감사합니다.

2024-07-31 07:23 UTC, racgoo commented on package.json
> +		"@types/moment": "^2.13.0",
저도 사용하고 싶었던 라이브러리라 어드민 API 끝나면 적용해볼게요!

2024-07-31 07:23 UTC, merged